project:
  type: book
  output-dir: docs

book:
  title: "PF-0953 Programación en R 2024-II"
  author: "Manuel Vargas"
  date: "2024-08-21"
  chapters:
    - index.qmd
    - programa_curso.qmd
    - part: parte-i-introduccion-programacion-computadoras-ciencia-datos.qmd
      chapters:
        - 01-introduccion-programacion-computadoras.qmd
        - 02-introduccion-ciencia-datos.qmd
    - part: parte-ii-lenguaje-programacion-r.qmd
      chapters:
        - 03-r.qmd        
    - part: parte-iii-herramientas-investigacion-reproducible-desarrollo-colaborativo.qmd        
      chapters:
        - 04-markdown.qmd   
        - 05-git.qmd   
        - 06-quarto.qmd   
    - part: parte-iv-graficacion-estadistica-r.qmd        
      chapters:
        - 07-tidyverse.qmd           
        - 08-dplyr.qmd           
        - 09-ggplot2-plotly.qmd
        - 10-introduccion-manejo-datos-geoespaciales.qmd
        - 11-modelos-nichos-ecologicos.qmd
        - 12-mapas-precipitacion.qmd
        - 13-modelos-nichos-ecologicos-proyeccion-clima-futuro.qmd

bibliography: referencias.bib
csl: apa-6th-edition.csl

format:
  html:
    lang: es
    theme: cosmo
    toc-expand: 5